### ISSUE TITLE
how to import dicts?

### ISSUE THREAD

**Issue by KonstantinDjairo** [rnpnr/jdict#1]
hello, nice project!
i wanted to know how can i import dictionaries, i tried to do what the README says, but couldn't get it working

![image](https://github.com/rnpnr/jdict/assets/53496273/bb71e54b-9769-4eeb-b76c-25ae87804b4a)

i've created a folder called daijirin and extracted the zip there, but even tho my config.h is configured correctly, it can't work

```/* dir where unzipped yomidicts are stored */
static char *prefix = "/mnt/Data/Japanese_Resources/languages-study(japanesAndRussian)/dicts/yomichan_format";

/* repl prompt and quit strings */
static char *repl_prompt = "\033[32;1m入力:\033[0m ";
static char *repl_quit = "\n\033[36m(=^ᆺ^)ﾉ　バイバイ～\033[0m";

/* default yomidicts to search */
static struct Dict {
	const char *rom;
	const char *name;
	size_t stride;
} default_dict_map[] = {
	{"daijirin", "【大辞林　第四版】", 100000},
	{"daijisen", "【大辞泉】", 10000},
	{"koujien", "【広辞苑】", 10000},
};
```

**Comment by rnpnr** [comment]
Hi, thanks for your interest in this project!

I just pushed a commit which should provide some better log messages. Can you try that and tell me the results?

**Comment by KonstantinDjairo** [comment]
it outputs that now:

```$ jdict 都下```
![image](https://github.com/rnpnr/jdict/assets/53496273/a0a47641-2145-4625-bf97-81cbc007623c)

**Comment by rnpnr** [comment]
Ok I see the problem. `yomidict.c` was written to accept dictionaries as they are output by yomichan-import. At some point people started embedding full json into the dictionaries and now those dictionaries are floating around the internet. They are not compatible with this tool.

Unfortunately its not possible to support those without implementing a full blown json lexer and parser. That isn't really within the scope of this project.

For the 3 dictionaries listed in `config.def.h` I just extract them myself directly from the epwing versions. I won't provide a link but another dictionary easily available online that is compatible with jdict has the filename: `[Monolingual] 旺文社国語辞典 第十一版 画像無し.zip`.

**Comment by KonstantinDjairo** [comment]
> Ok I see the problem. `yomidict.c` was written to accept dictionaries as they are output by yomichan-import. At some point people started embedding full json into the dictionaries and now those dictionaries are floating around the internet. They are not compatible with this tool.
> 
> Unfortunately its not possible to support those without implementing a full blown json lexer and parser. That isn't really within the scope of this project.
> 
> For the 3 dictionaries listed in `config.def.h` I just extract them myself directly from the epwing versions. I won't provide a link but another dictionary easily available online that is compatible with jdict has the filename: `[Monolingual] 旺文社国語辞典 第十一版 画像無し.zip`.

i see, so i'll stick to what im using currently, sdcv
